"""pgvector-backed retrieval of `orders` schema metadata.

The vector store holds *schema* documents, not business rows: the annotated
`CREATE TABLE` script generated by `backend/ddl_docs.py`, one document per
column (type, purpose comment and current distinct values) and a few
question -> SQL exemplars. The text-to-SQL planner retrieves the relevant ones
so it writes SQL against the real column names and real values instead of
guessing.

Embeddings go through the OpenAI-compatible endpoint in `ai_config`, the same
key and base URL the chat model uses.
"""

from sqlalchemy import select
from sqlalchemy.orm import Session

from backend.ai_config import EMBEDDING_MODEL, openai_client
from backend.models_db import SchemaDoc


def embed_texts(texts: list[str]) -> list[list[float]]:
    """Embed a batch. `encoding_format="float"` is required by Google AI Studio."""
    if not texts:
        return []
    response = openai_client().embeddings.create(
        model=EMBEDDING_MODEL, input=texts, encoding_format="float"
    )
    return [item.embedding for item in response.data]


def replace_schema_docs(db: Session, docs: dict[str, str]) -> int:
    """Re-embed and replace every schema document. Idempotent."""
    refs = list(docs)
    vectors = embed_texts([docs[ref] for ref in refs])

    db.query(SchemaDoc).delete()
    db.add_all(
        SchemaDoc(ref=ref, content=docs[ref], embedding=vector)
        for ref, vector in zip(refs, vectors)
    )
    db.commit()
    return len(refs)


def search_schema(db: Session, question: str, k: int = 8) -> list[SchemaDoc]:
    """Schema documents closest to `question` by cosine distance."""
    vector = embed_texts([question])[0]
    stmt = (
        select(SchemaDoc)
        .order_by(SchemaDoc.embedding.cosine_distance(vector))
        .limit(k)
    )
    return list(db.scalars(stmt))


def get_doc(db: Session, ref: str) -> str | None:
    """One document by ref, bypassing retrieval. Used for the always-on DDL."""
    return db.scalar(select(SchemaDoc.content).where(SchemaDoc.ref == ref))


def schema_context(
    db: Session, question: str, k: int = 8, exclude: str | None = None
) -> str:
    """Retrieved schema documents rendered as a prompt block.

    `exclude` skips a ref the caller already injects verbatim (the full DDL), so
    it does not take up a retrieval slot twice.
    """
    docs = search_schema(db, question, k + (1 if exclude else 0))
    if not docs:
        # Cold store (seeder not run yet): fall back to every document.
        docs = list(db.scalars(select(SchemaDoc)))
    if exclude:
        docs = [doc for doc in docs if doc.ref != exclude][:k]
    return "\n\n".join(f"[{doc.ref}]\n{doc.content}" for doc in docs)
