-- Generated by backend/ddl_docs.py from live Postgres introspection.
-- Do not edit by hand: `python -m backend.ddl_docs` rewrites it.

CREATE TABLE orders (
  order_id character varying NOT NULL,
  client_id character varying,
  order_date date,
  delivery_date date,
  carrier character varying,
  origin_city character varying,
  destination_city character varying,
  status character varying,
  sku character varying,
  product_category character varying,
  quantity integer,
  unit_price_usd numeric(10,2),
  order_value_usd numeric(12,2),
  is_promo boolean,
  promo_discount_pct integer,
  region character varying,
  warehouse character varying,
  PRIMARY KEY (order_id)
);

-- Comments
COMMENT ON TABLE orders IS 'Stores customer order transactions and fulfillment details to support sales reporting, revenue analysis, and logistics performance tracking.';
COMMENT ON COLUMN orders.order_id IS 'Holds the unique identifier for each order transaction, used to track distinct purchases and aggregate order-level metrics. 400 distinct values (too many to list).';
COMMENT ON COLUMN orders.client_id IS 'Holds the unique identifier of the customer placing the order, used to analyze customer retention, purchase frequency, and client lifetime value. 30 distinct values: ''CL-1001'', ''CL-1002'', ''CL-1003'', ''CL-1004'', ''CL-1005'', ''CL-1006'', ''CL-1007'', ''CL-1008'', ''CL-1009'', ''CL-1010'', ''CL-1011'', ''CL-1012'', ''CL-1013'', ''CL-1014'', ''CL-1015'', ''CL-1016'', ''CL-1017'', ''CL-1018'', ''CL-1019'', ''CL-1020'', ''CL-1021'', ''CL-1022'', ''CL-1023'', ''CL-1024'', ''CL-1025'', ''CL-1026'', ''CL-1027'', ''CL-1028'', ''CL-1029'', ''CL-1030''.';
COMMENT ON COLUMN orders.order_date IS 'Holds the date the order was created, used for sales trend analysis, cohort tracking, and seasonality studies.';
COMMENT ON COLUMN orders.delivery_date IS 'Holds the date the shipment arrived at the destination, used to calculate fulfillment lead times and monitor on-time delivery performance.';
COMMENT ON COLUMN orders.carrier IS 'Holds the name of the shipping service provider, used to evaluate carrier efficiency, transit times, and delivery reliability. 9 distinct values: ''DHL'', ''DPD'', ''FedEx'', ''GLS'', ''LaserShip'', ''OnTrac'', ''Royal Mail'', ''UPS'', ''USPS''.';
COMMENT ON COLUMN orders.origin_city IS 'Holds the departure city and state or country code of the shipment, used to map outbound distribution corridors and logistics flow. 9 distinct values: ''Amsterdam, NL'', ''Atlanta, GA'', ''Berlin, DE'', ''Chicago, IL'', ''Dallas, TX'', ''London, UK'', ''Los Angeles, CA'', ''Newark, NJ'', ''San Francisco, CA''.';
COMMENT ON COLUMN orders.destination_city IS 'Holds the recipient city and state or country code, used to map geographic demand concentration and optimize delivery routing. 47 distinct values: ''Austin, TX'', ''Baltimore, MD'', ''Birmingham, UK'', ''Boise, ID'', ''Boston, MA'', ''Brussels, BE'', ''Charlotte, NC'', ''Cleveland, OH'', ''Cologne, DE'', ''Denver, CO'', ''Detroit, MI'', ''Edinburgh, UK'', ''Frankfurt, DE'', ''Glasgow, UK'', ''Hamburg, DE'', ''Houston, TX'', ''Indianapolis, IN'', ''Kansas City, MO'', ''Las Vegas, NV'', ''Leeds, UK'', ''Manchester, UK'', ''Milwaukee, WI'', ''Minneapolis, MN'', ''Munich, DE'', ''Nashville, TN'', ''New York, NY'', ''Oklahoma City, OK'', ''Orlando, FL'', ''Paris, FR'', ''Philadelphia, PA'', ''Phoenix, AZ'', ''Portland, OR'', ''Prague, CZ'', ''Reno, NV'', ''Richmond, VA'', ''Sacramento, CA'', ''Salt Lake City, UT'', ''San Antonio, TX'', ''San Diego, CA'', ''San Jose, CA'', ''Seattle, WA'', ''St. Louis, MO'', ''Tampa, FL'', ''Vienna, AT'', ''Warsaw, PL'', ''Washington, DC'', ''Zurich, CH''.';
COMMENT ON COLUMN orders.status IS 'Holds the current operational state of the order, used to monitor fulfillment progress, cancellation rates, and shipment exceptions. 5 distinct values: ''canceled'', ''delayed'', ''delivered'', ''exception'', ''in_transit''.';
COMMENT ON COLUMN orders.sku IS 'Holds the stock keeping unit identifier for the ordered product, used to evaluate item-level velocity and inventory turnover. 355 distinct values (too many to list).';
COMMENT ON COLUMN orders.product_category IS 'Holds the classification group of the purchased item, used to analyze sales mix and category-level revenue contributions. 8 distinct values: ''BOOK'', ''BRUSH'', ''CRAYON'', ''MARKER'', ''PAINT'', ''PAPER'', ''PENCIL'', ''STICKER''.';
COMMENT ON COLUMN orders.quantity IS 'Holds the count of units ordered, used to measure sales volume, demand intensity, and average basket size.';
COMMENT ON COLUMN orders.unit_price_usd IS 'Holds the base price per unit in US dollars, used to evaluate product pricing tiers and unit-level profitability.';
COMMENT ON COLUMN orders.order_value_usd IS 'Holds the total monetary amount for the order line in US dollars, used as the core metric for financial reporting and total revenue analysis.';
COMMENT ON COLUMN orders.is_promo IS 'Holds a flag indicating whether the order received a promotional discount, used to evaluate marketing campaign participation and promo-driven volume.';
COMMENT ON COLUMN orders.promo_discount_pct IS 'Holds the discount percentage applied to the order, used to assess the depth of price promotions and analyze margin impact.';
COMMENT ON COLUMN orders.region IS 'Holds the geographic market code associated with the order, used to benchmark regional sales performance and logistics coverage. 5 distinct values: ''EU'', ''UK'', ''US-C'', ''US-E'', ''US-W''.';
COMMENT ON COLUMN orders.warehouse IS 'Holds the specific distribution facility handling the order, used to evaluate facility throughput, capacity utilization, and fulfillment efficiency. 9 distinct values: ''AMS-FC1'', ''ATL-DC1'', ''BER-FC1'', ''CHI-DC1'', ''DFW-DC1'', ''EWR-DC1'', ''LAX-DC1'', ''LON-FC1'', ''SFO-DC2''.';
